name: SoccerNet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - jupyter
  - notebook
  - ipykernel
  - pip:
      - torch
      - torchvision
      - ultralytics
      - soccernet
      - tqdm
      - pillow
      - pycocotools
      - opencv-python-headless
      - imagehash
